apiVersion: v1
kind: Service
metadata:
  name: kanban-ui
  labels: 
    group: backend
spec:
  type: NodePort
  selector:
    app: kanban-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30032