apiVersion: v1
kind: Service
metadata:
  name: kanban-app
  labels: 
    group: backend
spec:
  type: NodePort
  selector:
    app: kanban-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30030